# Generated by Django 5.2.14 on 2026-05-28 17:39

import MyWebApps.MNGTournament.models.Tournament
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationName', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizers',
                'ordering': ['organizationName'],
                'indexes': [models.Index(fields=['status'], name='idx_org_status')],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=100, unique=True)),
                ('logoUrl', models.URLField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['teamName'],
                'indexes': [models.Index(fields=['status'], name='idx_tea_status')],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamertag', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(blank=True, db_column='teams_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='MNGTournament.team')),
            ],
            options={
                'db_table': 'players',
                'ordering': ['gamertag'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=100)),
                ('tournamentTitle', models.CharField(max_length=150)),
                ('virtualPrize', models.CharField(blank=True, max_length=100, null=True)),
                ('maxParticipants', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2)])),
                ('eventDate', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(db_column='organizers_id', on_delete=django.db.models.deletion.RESTRICT, related_name='tournaments', to='MNGTournament.organizer')),
            ],
            options={
                'db_table': 'tournaments',
                'ordering': ['-eventDate', 'tournamentTitle'],
            },
        ),
        migrations.CreateModel(
            name='PlayerTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('finalPosition', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(db_column='players_id', on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to='MNGTournament.player')),
                ('tournament', models.ForeignKey(db_column='tournaments_id', on_delete=django.db.models.deletion.CASCADE, related_name='player_registrations', to='MNGTournament.tournament')),
            ],
            options={
                'db_table': 'players_tournaments',
            },
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['team'], name='idx_pla_teamsId'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['status'], name='idx_pla_status'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['organizer'], name='idx_tou_organizersId'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['eventDate'], name='idx_tou_eventDate'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['status'], name='idx_tou_status'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['gameName'], name='idx_tou_gameName'),
        ),
        migrations.AddIndex(
            model_name='playertournament',
            index=models.Index(fields=['player'], name='idx_pt_playersId'),
        ),
        migrations.AddIndex(
            model_name='playertournament',
            index=models.Index(fields=['tournament'], name='idx_pt_tournamentsId'),
        ),
        migrations.AddIndex(
            model_name='playertournament',
            index=models.Index(fields=['-score'], name='idx_pt_score'),
        ),
        migrations.AddIndex(
            model_name='playertournament',
            index=models.Index(fields=['finalPosition'], name='idx_pt_finalPosition'),
        ),
        migrations.AddIndex(
            model_name='playertournament',
            index=models.Index(fields=['status'], name='idx_pt_status'),
        ),
        migrations.AddConstraint(
            model_name='playertournament',
            constraint=models.UniqueConstraint(fields=('player', 'tournament'), name='uq_player_tournament'),
        ),
    ]
