# Generated by Django 6.0.6 on 2026-06-04 18:02

import MyWebApps.MNGTournament.models.Tournament
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNGTournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='organizationName',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='eventDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
